# Generated by Django 5.1.6 on 2025-04-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aniversariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('data', models.DateField()),
                ('idade', models.PositiveIntegerField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('sabor_preferido', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('M', 'masculino'), ('F', 'feminino'), ('O', 'outro')], max_length=1)),
            ],
        ),
    ]
