# Generated by Django 5.1.6 on 2025-03-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('descricao', models.TextField(max_length=100)),
                ('data_hora', models.DateTimeField()),
                ('local', models.CharField(blank=True, max_length=25, null=True)),
                ('categoria', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
