# Generated by Django 5.1.6 on 2025-03-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('idade', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
