# Generated by Django 5.1.6 on 2025-04-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disciplinas',
            new_name='Disciplina',
        ),
        migrations.RenameModel(
            old_name='Professores',
            new_name='Professor',
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'Professores'},
        ),
    ]
