# Generated by Django 5.2 on 2025-05-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='data_contratação',
            field=models.DateField(default='2000-1-1'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='data_nascimento',
            field=models.DateField(default='2000-1-1'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='ni',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='professor',
            name='telefone',
            field=models.IntegerField(default=1),
        ),
    ]
